#!/bin/bash

# Usage : vhost [ command [arguments] ]

# configs
source ./config.d/vhost.ini

# libs
source ./common/common.sh
source ./utils/vhost.sh

# get params and process command
# everything is in lowecase
command=${1,,}
arg1=${2,,}

#echo -e "1: ${command}, 2: ${arg1}"
#exit 0

# ensure root - this utility must be run as root
ensure_root

# ok to proceed
case "${command}" in

  "create") # create a vhost structure
    vhost-create "${arg1}"
    ;;

  "remove") # remove the vhost structure created above
    vhost-remove "${arg1}"
    ;;


  *) usage ;;

esac
